/**
 * Copyright (c) 1997, 2012, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * Generated By:JJTree: Do not edit this line. JDMTrapBlock.java
 */
/** Generated By:JJTree: Do not edit this line. JDMTrapBlock.java */
package com.sun.jmx.snmp.IPAcl;

import java.net.InetAddress;
import java.util.Hashtable;
import java.util.Vector;

class JDMTrapBlock extends SimpleNode{
    JDMTrapBlock(int id){
        super(id);
    }

    JDMTrapBlock(Parser p,int id){
        super(p,id);
    }

    public static Node jjtCreate(int id){
        return new JDMTrapBlock(id);
    }

    public static Node jjtCreate(Parser p,int id){
        return new JDMTrapBlock(p,id);
    }

    @Override
    public void buildInformEntries(Hashtable<InetAddress,Vector<String>> dest){
    }

    @Override
    public void buildAclEntries(PrincipalImpl owner,AclImpl acl){
    }
}
