/**
 * Copyright (c) 1997, 2007, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * Generated By:JJTree: Do not edit this line. JDMTrapInterestedHost.java
 */
/** Generated By:JJTree: Do not edit this line. JDMTrapInterestedHost.java */
package com.sun.jmx.snmp.IPAcl;

class JDMTrapInterestedHost extends SimpleNode{
    JDMTrapInterestedHost(int id){
        super(id);
    }

    JDMTrapInterestedHost(Parser p,int id){
        super(p,id);
    }

    public static Node jjtCreate(int id){
        return new JDMTrapInterestedHost(id);
    }

    public static Node jjtCreate(Parser p,int id){
        return new JDMTrapInterestedHost(p,id);
    }
}
