/**
 * Copyright (c) 1997, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * Generated By:JJTree: Do not edit this line. Node.java
 */
/** Generated By:JJTree: Do not edit this line. Node.java */
package com.sun.jmx.snmp.IPAcl;

interface Node{
    public void jjtOpen();

    public void jjtClose();

    public void jjtSetParent(Node n);

    public Node jjtGetParent();

    public void jjtAddChild(Node n,int i);

    public Node jjtGetChild(int i);

    public int jjtGetNumChildren();
}
