/**
 * Copyright (c) 1997, 2003, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * <p>
 * Generated By:JavaCC: Do not edit this line. Token.java Version 0.7pre3
 */
/** Generated By:JavaCC: Do not edit this line. Token.java Version 0.7pre3 */
package com.sun.jmx.snmp.IPAcl;

class Token{
    public int kind;
    public int beginLine, beginColumn, endLine, endColumn;
    public String image;
    public Token next;
    public Token specialToken;

    public static final Token newToken(int ofKind){
        switch(ofKind){
            default:
                return new Token();
        }
    }

    public final String toString(){
        return image;
    }
}
