/**
 * Copyright (c) 1999, 2000, Oracle and/or its affiliates. All rights reserved.
 * ORACLE PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 * <p>
 * Licensed Materials - Property of IBM
 * RMI-IIOP v1.0
 * Copyright IBM Corp. 1998 1999  All Rights Reserved
 */
/**
 * Licensed Materials - Property of IBM
 * RMI-IIOP v1.0
 * Copyright IBM Corp. 1998 1999  All Rights Reserved
 *
 */
// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.
package org.omg.stub.java.rmi;

import javax.rmi.CORBA.Stub;
import java.rmi.Remote;

public final class _Remote_Stub extends Stub implements Remote{
    private static final String _type_ids[]={
            ""
    };

    public String[] _ids(){
        return (String[])_type_ids.clone();
    }
}
